apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: alb
  labels:
    app: {{ include "web.name" . }}-ingress

spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "web.fullname" $ }}-service
            port:
              number: 80
