apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "web.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: alb
  labels:
    app: {{ include "web.name" . }}-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ include "web.fullname" . }}-service
              servicePort: 80
